-- ============================================
-- Bulk import — 200 keywords expandidas
-- Ejecutar DESPUÉS de schema.sql y keywords-initial
-- ============================================

WITH niche_ids AS (
  SELECT slug, id FROM niches
)
INSERT INTO keywords (keyword, niche_id, article_type, intent, priority, status)
VALUES
-- AI Writing (50)
('Jasper vs Anyword: which is better for ads', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'comparison', 'commercial', 8, 'queued'),
('ContentBot vs Copy.ai', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'comparison', 'commercial', 7, 'queued'),
('Writesonic vs Rytr', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'comparison', 'commercial', 7, 'queued'),
('Jasper vs Surfer SEO integration', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'comparison', 'commercial', 8, 'queued'),
('ChatGPT vs Claude for writing', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'comparison', 'commercial', 10, 'queued'),
('Copy.ai vs Hypotenuse AI', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'comparison', 'commercial', 6, 'queued'),
('Scalenut vs Jasper', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'comparison', 'commercial', 7, 'queued'),
('INK vs Frase for SEO writing', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'comparison', 'commercial', 7, 'queued'),
('Wordtune vs Grammarly Premium', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'comparison', 'commercial', 8, 'queued'),
('Koala AI vs Jasper', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'comparison', 'commercial', 7, 'queued'),
('GetGenie AI vs Koala AI', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'comparison', 'commercial', 6, 'queued'),
('Writesonic Chatsonic vs ChatGPT Plus', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'comparison', 'commercial', 7, 'queued'),
('Jasper vs Lex.page for books', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'comparison', 'commercial', 6, 'queued'),
('Sudowrite vs NovelAI for fiction', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'comparison', 'commercial', 6, 'queued'),
('Best AI tools for SEO content 2026', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'listicle', 'commercial', 10, 'queued'),
('Best AI writing tools under $30/month', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'listicle', 'commercial', 9, 'queued'),
('Best AI writing tools for agencies', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'listicle', 'commercial', 8, 'queued'),
('Best AI tool for writing YouTube scripts', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'listicle', 'commercial', 9, 'queued'),
('Best AI for writing Twitter threads', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'listicle', 'commercial', 8, 'queued'),
('Best AI for writing LinkedIn posts that go viral', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'listicle', 'commercial', 8, 'queued'),
('Best AI for writing email newsletters', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'listicle', 'commercial', 8, 'queued'),
('Best AI for writing sales pages', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'listicle', 'commercial', 9, 'queued'),
('Best AI for writing Amazon product descriptions', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'listicle', 'commercial', 8, 'queued'),
('Best AI writing tools for non-native English speakers', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'listicle', 'commercial', 7, 'queued'),
('Best AI writing tools for academic writing', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'listicle', 'commercial', 7, 'queued'),
('Best AI writing tools for fiction authors', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'listicle', 'commercial', 7, 'queued'),
('Best AI writing tools for journalists', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'listicle', 'commercial', 6, 'queued'),
('Best AI writing tools for Spanish content', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'listicle', 'commercial', 8, 'queued'),
('Best AI tools to rewrite articles', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'listicle', 'commercial', 8, 'queued'),
('Best AI for generating headlines that convert', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'listicle', 'commercial', 8, 'queued'),
('Anyword review: is it worth it for ads', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'review', 'commercial', 7, 'queued'),
('Wordtune review: does it actually help', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'review', 'commercial', 7, 'queued'),
('Rytr review: AI writing on a budget', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'review', 'commercial', 7, 'queued'),
('Sudowrite review: AI for fiction writers', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'review', 'commercial', 6, 'queued'),
('Koala AI review: ChatGPT killer?', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'review', 'commercial', 8, 'queued'),
('Scalenut review: SEO + content in one', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'review', 'commercial', 7, 'queued'),
('Frase review: content briefs with AI', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'review', 'commercial', 7, 'queued'),
('Surfer SEO + Jasper review combo', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'review', 'commercial', 7, 'queued'),
('Hypotenuse AI review', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'review', 'commercial', 6, 'queued'),
('ContentBot review 2026', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'review', 'commercial', 6, 'queued'),
('How to use Jasper to write SEO blog posts', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'how-to', 'informational', 7, 'queued'),
('How to use Copy.ai for Facebook ads', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'how-to', 'informational', 7, 'queued'),
('How to train AI on your writing style', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'how-to', 'informational', 6, 'queued'),
('How to avoid AI detection while using AI writers', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'how-to', 'informational', 9, 'queued'),
('How to edit AI-generated content to make it human', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'how-to', 'informational', 8, 'queued'),
('How to use ChatGPT for cold email outreach', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'how-to', 'informational', 7, 'queued'),
('How to write better prompts for AI writing', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'how-to', 'informational', 8, 'queued'),
('How to use AI to scale affiliate blogging', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'how-to', 'informational', 9, 'queued'),
('Free alternatives to Jasper AI', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'alternatives', 'commercial', 9, 'queued'),
('Jasper alternatives that are cheaper', (SELECT id FROM niche_ids WHERE slug='ai-writing'), 'alternatives', 'commercial', 9, 'queued'),

-- AI Business (45)
('Zapier vs Make vs n8n for automation', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'comparison', 'commercial', 10, 'queued'),
('Airtable vs Notion vs Coda', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'comparison', 'commercial', 10, 'queued'),
('Monday.com vs Asana vs ClickUp', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'comparison', 'commercial', 10, 'queued'),
('Calendly vs SavvyCal vs Cal.com', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'comparison', 'commercial', 8, 'queued'),
('HubSpot vs Pipedrive vs Close', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'comparison', 'commercial', 9, 'queued'),
('Slack vs Discord for teams', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'comparison', 'informational', 8, 'queued'),
('Loom vs Vidyard for async video', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'comparison', 'commercial', 7, 'queued'),
('Fireflies vs Otter vs Fathom', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'comparison', 'commercial', 8, 'queued'),
('Lemlist vs Instantly vs Smartlead for cold email', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'comparison', 'commercial', 9, 'queued'),
('Apollo vs ZoomInfo for prospecting', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'comparison', 'commercial', 8, 'queued'),
('Beehiiv vs Substack vs ConvertKit', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'comparison', 'commercial', 9, 'queued'),
('Linear vs Jira for dev teams', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'comparison', 'commercial', 8, 'queued'),
('Miro vs FigJam vs Whimsical', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'comparison', 'commercial', 7, 'queued'),
('Pitch vs Gamma vs Beautiful.ai for AI presentations', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'comparison', 'commercial', 8, 'queued'),
('Descript vs Riverside for podcast editing', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'comparison', 'commercial', 7, 'queued'),
('Best AI CRM tools 2026', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'listicle', 'commercial', 9, 'queued'),
('Best AI tools for e-commerce stores', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'listicle', 'commercial', 9, 'queued'),
('Best AI tools for marketing agencies', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'listicle', 'commercial', 9, 'queued'),
('Best AI tools for sales teams', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'listicle', 'commercial', 9, 'queued'),
('Best AI tools for HR and recruiting', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'listicle', 'commercial', 8, 'queued'),
('Best AI tools for customer support', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'listicle', 'commercial', 8, 'queued'),
('Best AI schedulers', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'listicle', 'commercial', 7, 'queued'),
('Best AI meeting assistants', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'listicle', 'commercial', 8, 'queued'),
('Best AI tools for project managers', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'listicle', 'commercial', 8, 'queued'),
('Best AI tools for remote teams', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'listicle', 'commercial', 8, 'queued'),
('Best AI tools for freelancers', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'listicle', 'commercial', 8, 'queued'),
('Best AI tools for consultants', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'listicle', 'commercial', 7, 'queued'),
('Best AI tools for startups', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'listicle', 'commercial', 9, 'queued'),
('Best AI note-taking apps', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'listicle', 'commercial', 8, 'queued'),
('Best AI email apps', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'listicle', 'commercial', 8, 'queued'),
('Make.com review: the Zapier alternative', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'review', 'commercial', 9, 'queued'),
('HubSpot free plan review: worth starting with', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'review', 'commercial', 8, 'queued'),
('Pipedrive review 2026', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'review', 'commercial', 7, 'queued'),
('Fathom review: AI meeting notes', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'review', 'commercial', 7, 'queued'),
('Beehiiv review: the Substack killer', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'review', 'commercial', 8, 'queued'),
('Linear review: why devs love it', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'review', 'commercial', 7, 'queued'),
('Close CRM review', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'review', 'commercial', 6, 'queued'),
('Apollo.io review', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'review', 'commercial', 7, 'queued'),
('ClickUp vs all-in-one tools', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'review', 'commercial', 7, 'queued'),
('Coda review 2026', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'review', 'commercial', 7, 'queued'),
('How to automate your e-commerce with AI', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'how-to', 'informational', 8, 'queued'),
('How to use AI to qualify leads', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'how-to', 'informational', 8, 'queued'),
('How to build an AI chatbot for your website', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'how-to', 'informational', 8, 'queued'),
('How to automate customer service with AI', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'how-to', 'informational', 7, 'queued'),
('How to use AI to write meeting summaries', (SELECT id FROM niche_ids WHERE slug='ai-business'), 'how-to', 'informational', 6, 'queued');

-- Keywords restantes (image/video, coding, hosting, creators) se agregan con el mismo patrón
-- Total al finalizar: ~250 keywords queued

SELECT COUNT(*) AS total_queued FROM keywords WHERE status = 'queued';
