#!/usr/bin/env node
/**
 * AIPickd — Dynamic Sitemap Updater
 *
 * Fetches all published articles from Supabase, generates a sitemap.xml,
 * and uploads/pings it. Run after batch publishes.
 *
 * Features:
 *   - Generates sitemap from Supabase published articles
 *   - Prioritizes articles by recency and type
 *   - Pings Google + Bing with the sitemap URL
 *   - Optionally saves sitemap to disk for manual upload
 *
 * Usage:
 *   node scripts/sitemap-update.js                # generate + ping
 *   node scripts/sitemap-update.js --save         # also save to sitemap-generated.xml
 *   node scripts/sitemap-update.js --dry-run      # generate but don't ping
 */

const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '..', '.env');
// Start with process.env so GitHub Actions secrets work without a .env file
const env = { ...process.env };
try {
  fs.readFileSync(envPath, 'utf8').split('\n').forEach((line) => {
    const m = line.match(/^([A-Z0-9_]+)="?([^"\n]*)"?$/);
    if (m) env[m[1]] = m[2]; // local .env overrides when present
  });
} catch {}

const SAVE = process.argv.includes('--save');
const DRY_RUN = process.argv.includes('--dry-run');
const SITE_URL = 'https://aipickd.com';
const SITEMAP_URL = `${SITE_URL}/sitemap.xml`; // WordPress auto-generates this

// Priority by article type
const TYPE_PRIORITY = {
  list:       '0.9',
  comparison: '0.85',
  review:     '0.85',
  'how-to':   '0.8',
  guide:      '0.75',
  default:    '0.7',
};

// Change frequency by age
function getChangefreq(publishedAt) {
  const days = (Date.now() - new Date(publishedAt).getTime()) / 86400000;
  if (days < 7)   return 'daily';
  if (days < 30)  return 'weekly';
  if (days < 180) return 'monthly';
  return 'yearly';
}

async function supa(endpoint) {
  const r = await fetch(`${env.SUPABASE_URL}/rest/v1/${endpoint}`, {
    headers: {
      apikey: env.SUPABASE_SERVICE_ROLE_KEY,
      Authorization: `Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,
    },
  });
  if (!r.ok) throw new Error(`Supabase: ${r.status}`);
  return r.json();
}

(async () => {
  console.log('🗺️ AIPickd Sitemap Updater\n');

  // Fetch all published articles with URLs
  const articles = await supa(
    'articles?status=eq.published&wp_url=not.is.null&select=id,wp_url,title,article_type,published_at,word_count&order=published_at.desc'
  );

  if (!Array.isArray(articles) || articles.length === 0) {
    console.log('⚠️ No published articles found.');
    return;
  }

  console.log(`Found ${articles.length} published articles\n`);

  // Generate sitemap XML
  const now = new Date().toISOString();
  const entries = articles.map(a => {
    const priority = TYPE_PRIORITY[a.article_type] || TYPE_PRIORITY.default;
    const changefreq = getChangefreq(a.published_at);
    const lastmod = a.published_at ? new Date(a.published_at).toISOString().slice(0, 10) : now.slice(0, 10);
    return `  <url>
    <loc>${a.wp_url}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`;
  }).join('\n');

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
        http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
  <!-- Generated by AIPickd pipeline — ${now} -->
  <!-- ${articles.length} articles -->

  <!-- Homepage -->
  <url>
    <loc>${SITE_URL}/</loc>
    <lastmod>${now.slice(0, 10)}</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>

${entries}
</urlset>`;

  console.log(`Generated sitemap with ${articles.length + 1} URLs`);
  console.log(`  Newest: ${articles[0]?.wp_url || 'N/A'}`);
  console.log(`  Oldest: ${articles[articles.length - 1]?.wp_url || 'N/A'}`);

  if (SAVE) {
    const outPath = path.join(__dirname, '..', 'sitemap-generated.xml');
    fs.writeFileSync(outPath, xml);
    console.log(`\n📄 Saved to: sitemap-generated.xml`);
  }

  if (DRY_RUN) {
    console.log('\n[dry-run] Skipping sitemap pings.');
    console.log(xml.slice(0, 500) + '...');
    return;
  }

  // Ping search engines with the WordPress sitemap URL (WP generates its own)
  // We use the WP-generated one since it includes categories, tags, pages
  console.log(`\n🔔 Pinging search engines with: ${SITEMAP_URL}`);

  const pings = [
    // Google (submit via GSC API, or just fetch to refresh their crawler)
    `https://www.google.com/ping?sitemap=${encodeURIComponent(SITEMAP_URL)}`,
    // Bing
    `https://www.bing.com/indexnow?url=${encodeURIComponent(SITEMAP_URL)}&key=${env.INDEXNOW_KEY || 'aipickd2026'}`,
    // IndexNow API
    `https://api.indexnow.org/indexnow?url=${encodeURIComponent(SITEMAP_URL)}&key=${env.INDEXNOW_KEY || 'aipickd2026'}`,
  ];

  const results = await Promise.allSettled(
    pings.map(url => fetch(url, { signal: AbortSignal.timeout(10000) }).then(r => ({ url, status: r.status, ok: r.ok })))
  );

  results.forEach(r => {
    if (r.status === 'fulfilled') {
      console.log(`  ${r.value.ok ? '✅' : '⚠️'} ${new URL(r.value.url).hostname} → ${r.value.status}`);
    } else {
      console.log(`  ❌ ${r.reason?.message || 'failed'}`);
    }
  });

  console.log('\n✅ Sitemap update complete!');
  console.log(`\n💡 WordPress generates sitemap at: ${SITEMAP_URL}`);
  console.log('   Ensure Yoast SEO or RankMath sitemap is enabled in WordPress.');
})().catch((e) => {
  console.error('❌ Sitemap update failed:', e.message);
  process.exit(1);
});
